/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from Stage0_emmc.bin */
static const unsigned char bin2c_Stage0_emmc_bin[64] = {'=','@',02,'@','a','J',0,0377,'y','J',0203,0344,'a','J',0363,010,'9',' ',01,0200,'}',')',03,0246,0221,'*',0,024,0200,'j',0,0,'p','c',0,037,'A',0202,0377,0370,0200,'j',0,030,0230,'i',0,0,'9',')',0,01,',',011,02,0,'@',0202,0377,0344,'N',0200,04,' ',};

#ifdef __cplusplus
} /* extern "C" */
#endif
